services:
  frontend1:
    image: node:22-slim
    ports:
      - "3001:3000"
    volumes:
      - ./client:/etc/client
      - node_modules:/etc/client/node_modules
      - next:/etc/client/example/multiple/.next/
    working_dir: /etc/client
    environment:
      NEXT_PUBLIC_SERVER_PORT: 4001
    command: bash -c "yarn install && yarn workspace rheomesh build && yarn workspace multiple dev -H 0.0.0.0"
  frontend2:
    image: node:22-slim
    ports:
      - "3002:3000"
    volumes:
      - ./client:/etc/client
      - node_modules:/etc/client/node_modules
      - next:/etc/client/example/multiple/.next
    working_dir: /etc/client
    environment:
      NEXT_PUBLIC_SERVER_PORT: 4002
    command: bash -c "yarn install && yarn workspace rheomesh build && yarn workspace multiple dev -H 0.0.0.0"

  sfu1:
    image: rust:1.84.1-slim
    ports:
      - "4001:4000"
    volumes:
      - ./sfu:/etc/sfu
      - target:/etc/sfu/target
    working_dir: /etc/sfu
    command: cargo run --example relay_server
  sfu2:
    image: rust:1.84.1-slim
    ports:
      - "4002:4000"
    volumes:
      - ./sfu:/etc/sfu
      - target:/etc/sfu/target
    working_dir: /etc/sfu
    command: cargo run --example relay_server

volumes:
  next:
  node_modules:
  target:
