name: Build

on:
  push:
    branches: [ "master" ]
    tags:
  pull_request:


jobs:
  sfu:
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: ./sfu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace rheomesh run build
          yarn workspace media run build
          yarn workspace data run build
      - name: Test
        run: |
          yarn workspace rheomesh test
