name: Docs

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.10'
        bundler-cache: true
    - run: bundle install
    - run: bundle exec jekyll build
